/// Agam Compiler Driver
///
/// Full pipeline: Source -> Lex -> Parse -> HIR -> THIR -> MIR -> LLVM IR -> [Optimize] -> Codegen/Execute
///
/// Usage:
///   agamc <input.agam> [-o output] [--emit-ast] [--emit-hir] [--emit-thir] [--emit-mir]
///                      [--emit-llvm] [-O0|-O1|-O2|-O3] [--run]

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <memory>
#include <set>
#include <filesystem>

#include "agam/lexer/lexer.h"
#include "agam/parser/parser.h"
#include "agam/ast/ast_printer.h"
#include "agam/semantic/scope_resolver.h"
#include "agam/semantic/type_checker.h"
#include "agam/semantic/monomorphizer.h"
#include "agam/hir/hir_builder.h"
#include "agam/thir/thir_builder.h"
#include "agam/mir/mir_builder.h"
#include "agam/mir/mir_printer.h"
#include "agam/mir/mir_optimizer.h"
#include "agam/codegen/codegen.h"
#include "agam/codegen/optimizer.h"
#include "agam/codegen/executor.h"
#include "agam/utils/diagnostic_renderer.h"

#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/IR/LegacyPassManager.h"

using namespace agam;
namespace fs = std::filesystem;

// Global diagnostic infrastructure
SourceManager g_sourceManager;
DiagnosticEngine g_diagEngine(g_sourceManager);

static void printUsage(const char *prog) {
    std::cout << "அகம் (Agam) கம்பைலர் பதிப்பு " << AGAM_VERSION << "\n"
              << "பயன்பாடு: " << prog << " [விருப்பங்கள்] <input.agam>\n"
              << "          " << prog << " create <திட்டப்பொருள்_பெயர்> | .\n"
              << "          " << prog << " run [கோப்பு_பெயர்]\n"
              << "\nவிருப்பங்கள் (Options):\n"
              << "  -o, --output <கோப்பு>   வெளியீட்டு கோப்பினை குறிப்பிடுக (இயல்பு: a.out / a.exe)\n"
              << "  -v, --version         பதிப்பு தகவலை அச்சிடுக\n"
              << "  -h, --help            இந்த உதவிச் செய்தியை அச்சிடுக\n"
              << "  --emit-ast            AST-ஐ அச்சிட்டு வெளியேறுக\n"
              << "  --emit-hir            HIR-ஐ அச்சிட்டு வெளியேறுக\n"
              << "  --emit-thir           THIR வகைகளை அச்சிட்டு வெளியேறுக\n"
              << "  --emit-mir            MIR-ஐ அச்சிட்டு வெளியேறுக\n"
              << "  --emit-llvm           LLVM IR-ஐ அச்சிட்டு வெளியேறுக\n"
              << "  -O<n>                 மேம்படுத்தல் நிலை (Optimization level) (0-3, இயல்பு: 0)\n"
              << "  --run                 கம்பைல் செய்வதற்கு பதிலாக JIT மூலம் இயக்குக\n"
              << "  --lib-path <பாதை>     தனிப்பயன் தரநிலை நூலகப் பாதையைக் குறிப்பிடுக\n";
}

static int handleCreate(int argc, char *argv[]) {
    if (argc < 3) {
        std::cerr << "பிழை: 'create' செய்வதற்கு திட்டப்பொருள் பெயர் (project name) தேவை\n";
        return 1;
    }

    std::string projNameArg = argv[2];
    fs::path projectRoot;

    if (projNameArg == ".") {
        projectRoot = fs::current_path();
    } else {
        projectRoot = fs::current_path() / projNameArg;
        if (!fs::exists(projectRoot)) {
            fs::create_directory(projectRoot);
        }
    }

    fs::path srcDir = projectRoot / "src";
    if (!fs::exists(srcDir)) fs::create_directory(srcDir);

    // Create pk.arpk
    std::ofstream arpk(projectRoot / "pk.arpk");
    std::string name = (projNameArg == ".") ? projectRoot.filename().string() : projNameArg;
    arpk << "projectname: \"" << name << "\"\n"
         << "version: \"0.1.0\"\n"
         << "author: \"\"\n\n"
         << "#dependencies\n"
         << "[name]: [version]\n"
         << "std: 1.0.0,\n\n"
         << "#dev_dep\n"
         << "[name]: [version]\n"
         << "std: 1.0.0,\n";
    arpk.close();

    // Create src/main.agam
    std::ofstream mainAgam(srcDir / "main.agam");
    mainAgam << "செயல் மைய(): எண் {\n"
             << "    விடை 0;\n"
             << "}\n";
    mainAgam.close();

    // Create README.md
    std::ofstream readme(projectRoot / "README.md");
    readme << "# " << name << "\n\nGenerated by Agam Compiler.\n";
    readme.close();

    std::cout << "திட்டப்பொருள் (Project) '" << name << "' வெற்றிகரமாக உருவாக்கப்பட்டது.\n";
    return 0;
}

namespace agam {

static std::string trim(const std::string& s) {
    auto start = s.begin();
    while (start != s.end() && std::isspace(*start)) start++;
    auto end = s.end();
    do { end--; } while (std::distance(start, end) > 0 && std::isspace(*end));
    return std::string(start, end + 1);
}

static fs::path g_exeDir;
static std::string g_stdEnvPath;

std::unique_ptr<Program> parseWithImports(const std::string &filename, std::set<std::string> &visited) {
    fs::path targetPath = fs::absolute(filename);
    
    // If not found, it might be a library import without full path
    if (!fs::exists(targetPath)) {
        std::cerr << "பிழை: எந்தத் தேடல் பாதையிலும் '" << filename << "' என்ற கோப்பினைத் தேட முடியவில்லை\n";
        return nullptr;
    }

    std::string absolutePath = targetPath.string();
    if (visited.count(absolutePath)) return nullptr;
    visited.insert(absolutePath);

    std::ifstream file(absolutePath);
    if (!file.is_open()) {
        std::cerr << "பிழை: '" << absolutePath << "' என்ற கோப்பினைத் திறக்க முடியவில்லை\n";
        return nullptr;
    }
    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string source = buffer.str();

    g_sourceManager.addSource(absolutePath, source);

    // Lex
    Lexer lexer(source, absolutePath, g_diagEngine);
    auto tokens = lexer.tokenize();
    if (g_diagEngine.hasErrors()) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return nullptr;
    }

    // Parse
    Parser parser(tokens, source, absolutePath, g_diagEngine);
    auto ast = parser.parse();
    if (g_diagEngine.hasErrors()) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return nullptr;
    }

    auto master = std::move(ast);
    auto baseDir = fs::path(absolutePath).parent_path();

    // Recursively handle imports
    std::vector<std::string> discoveredImports = master->imports;
    for (const auto &imp : discoveredImports) {
        fs::path impPath = baseDir / imp;
        bool found = false;
        
        // 1. Try relative to current file
        if (impPath.extension().empty()) impPath.replace_extension(".agam");
        if (fs::exists(impPath)) {
            found = true;
        }

        // 2. Try AGAM_STD_PATH
        if (!found && !g_stdEnvPath.empty()) {
            fs::path envPath = fs::path(g_stdEnvPath) / imp;
            if (envPath.extension().empty()) envPath.replace_extension(".agam");
            if (fs::exists(envPath)) {
                impPath = envPath;
                found = true;
            }
        }
        
        // 3. Try relative to executable
        if (!found) {
            std::vector<fs::path> sysPaths = {
                g_exeDir / ".." / "share" / "agam" / imp,
                g_exeDir / ".." / imp,
                g_exeDir / ".." / ".." / imp
            };
            for (auto &sp : sysPaths) {
                if (sp.extension().empty()) sp.replace_extension(".agam");
                if (fs::exists(sp)) {
                    impPath = sp;
                    found = true;
                    break;
                }
            }
        }

        if (!found) {
            std::cerr << "பிழை: இறக்குமதி செய்யப்பட வேண்டிய '" << imp << "' என்ற பெயரைக் காணவில்லை.\n";
            std::cerr << "  (அடிப்படைப் பாதை: " << baseDir << ")\n";
            if (!g_stdEnvPath.empty()) {
                fs::path envPath = fs::path(g_stdEnvPath) / imp;
                if (envPath.extension().empty()) envPath.replace_extension(".agam");
                std::cerr << "  (AGAM_STD_PATH check: " << envPath << " exists=" << (fs::exists(envPath) ? "true" : "false") << ")\n";
            }
            return nullptr;
        }

        auto subProg = parseWithImports(impPath.string(), visited);
        if (subProg) {
            // Merge declarations into master (flat namespace for now)
            for (auto &f : subProg->functions) master->functions.push_back(std::move(f));
            for (auto &s : subProg->structs) master->structs.push_back(std::move(s));
            for (auto &e : subProg->enums) master->enums.push_back(std::move(e));
            for (auto &t : subProg->traits) master->traits.push_back(std::move(t));
            for (auto &i : subProg->impls) master->impls.push_back(std::move(i));
            for (auto &c : subProg->constants) master->constants.push_back(std::move(c));
        }
    }

    return master;
}

} // namespace agam

int main(int argc, char *argv[]) {
    g_exeDir = fs::absolute(argv[0]).parent_path();
    const char* envPath = std::getenv("AGAM_STD_PATH");
    if (envPath) g_stdEnvPath = trim(envPath);

    if (argc < 2) {
        printUsage(argv[0]);
        return 1;
    }

    std::string inputFile;
    std::string outputFile;
    bool emitAst = false, emitHir = false, emitThir = false, emitMir = false, emitLlvm = false;
    bool runJit = false;
    Optimizer::Level optLevel = Optimizer::Level::O0;

    int argStart = 1;

    // Pre-scan for -C flag
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "-C" && i + 1 < argc) {
            fs::current_path(argv[i+1]);
            // Re-order or skip? Let's just handle it here and we'll skip it in the main loop
        }
    }

    // Check for subcommands
    std::string firstArg = argv[1];
    if (firstArg == "create") {
        return handleCreate(argc, argv);
    } else if (firstArg == "run") {
        runJit = true;
        argStart = 2;
        // Re-check pk.arpk after possible -C
        if (fs::exists("pk.arpk")) {
            if (fs::exists("src/main.agam")) {
                inputFile = "src/main.agam";
            } else {
                std::cerr << "பிழை: 'pk.arpk' உள்ளது, ஆனால் 'src/main.agam' கோப்பைக் காணவில்லை.\n";
                return 1;
            }
        } else {
            // Check for file in arguments, skipping -C and its value
            for (int i = 2; i < argc; i++) {
                std::string arg = argv[i];
                if (arg == "-C") { i++; continue; }
                if (arg[0] != '-') {
                    inputFile = arg;
                    argStart = i + 1;
                    break;
                }
            }
            if (inputFile.empty()) {
                std::cerr << "பிழை: 'pk.arpk' கோப்பு இல்லை மற்றும் 'run' செய்ய வேண்டிய கோப்பும் குறிப்பிடப்படவில்லை.\n";
                return 1;
            }
        }
    }

    for (int i = argStart; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "-C") {
            i++; // skip
            continue;
        }
        if ((arg == "-o" || arg == "--output") && i + 1 < argc) {
            outputFile = argv[++i];
        } else if (arg == "--emit-ast") {
            emitAst = true;
        } else if (arg == "--emit-hir") {
            emitHir = true;
        } else if (arg == "--emit-thir") {
            emitThir = true;
        } else if (arg == "--emit-mir") {
            emitMir = true;
        } else if (arg == "--emit-llvm") {
            emitLlvm = true;
        } else if (arg == "--run") {
            runJit = true;
        } else if (arg == "-v" || arg == "--version") {
            std::cout << "அகம் (Agam) கம்பைலர் பதிப்பு " << AGAM_VERSION << "\n";
            return 0;
        } else if (arg == "-h" || arg == "--help") {
            printUsage(argv[0]);
            return 0;
        } else if (arg == "--lib-path" && i + 1 < argc) {
            // libPath = argv[++i]; // TODO: implement std search path
            i++;
        } else if (arg.substr(0, 2) == "-O" && arg.size() == 3) {
            optLevel = Optimizer::parseLevel(arg.substr(2));
        } else if (arg[0] != '-') {
            inputFile = arg;
        } else {
            std::cerr << "அறியப்படாத விருப்பம்: " << arg << "\n";
            printUsage(argv[0]);
            return 1;
        }
    }

    if (inputFile.empty()) {
        std::cerr << "பிழை: உள்ளீட்டு கோப்பு (input file) இல்லை\n";
        return 1;
    }

    // ── Parse with Imports ──────────────────────────────────────────────────
    std::set<std::string> visited;
    auto ast = parseWithImports(inputFile, visited);
    if (!ast) {
        return 1;
    }

    if (emitAst) {
        ASTPrinter printer;
        ast->accept(printer);
        return 0;
    }

    // ── Semantic Analysis ──────────────────────────────────────────────────
    ScopeResolver scopeResolver;
    if (!scopeResolver.resolve(*ast, g_diagEngine)) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return 1;
    }

    TypeChecker typeChecker;
    if (!typeChecker.check(*ast, g_diagEngine)) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return 1;
    }

    // ── Monomorphization ──────────────────────────────────────────────────
    // Check for main function in the entry AST.
    bool hasMain = false;
    for (const auto &fn : ast->functions) {
        if (fn->name == "மைய") {
            hasMain = true;
            break;
        }
    }
    if (!hasMain) {
        std::cerr << "பிழை: " << inputFile << " இல் 'மைய' (main) செயல்பாடு காணப்படவில்லை\n";
        return 1;
    }

    Monomorphizer monomorphizer;
    monomorphizer.monomorphize(*ast);

    // Re-run semantic analysis on specialized nodes
    g_diagEngine.clear();
    if (!scopeResolver.resolve(*ast, g_diagEngine)) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return 1;
    }
    if (!typeChecker.check(*ast, g_diagEngine)) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return 1;
    }

    // ── HIR ─────────────────────────────────────────────────────────────────
    HirBuilder hirBuilder;
    auto hir = hirBuilder.build(*ast);
    if (hirBuilder.hasErrors()) {
        for (auto &e : hirBuilder.errors()) std::cerr << e << "\n";
        return 1;
    }

    if (emitHir) {
        std::cout << "=== HIR ===" << std::endl;
        for (auto &fn : hir->functions) {
            std::cout << "fn " << fn->name << " (id=" << fn->id << ")";
            std::cout << " -> " << typeKindToString(fn->returnTypeInfo.kind) << std::endl;
        }
        return 0;
    }

    // ── Lower to THIR ──────────────────────────────────────────────────────
    ThirBuilder thirBuilder;
    auto thir = thirBuilder.build(*hir, g_diagEngine);
    if (!thir || g_diagEngine.hasErrors()) {
        DiagnosticRenderer::renderToTerminal(g_diagEngine);
        return 1;
    }

    if (emitThir) {
        for (auto &fn : thir->functions) {
            std::cout << "fn " << fn->name << " -> " << typeKindToString(fn->returnTypeInfo.kind) << std::endl;
        }
        return 0;
    }

    // ── MIR ─────────────────────────────────────────────────────────────────
    MirBuilder mirBuilder;
    auto mir = mirBuilder.build(*thir);

    // ── MIR Optimization ───────────────────────────────────────────────────
    if (optLevel != Optimizer::Level::O0) {
        MirOptimizer::optimize(*mir);
    }

    if (emitMir) {
        std::cout << MirPrinter::print(*mir);
        return 0;
    }

    // ── Codegen ─────────────────────────────────────────────────────────────
    CodeGenerator codegen;
    if (!codegen.generate(*mir)) {
        std::cerr << "பிழை: குறியாக்கத்தில் (code generation) பிழை ஏற்பட்டது\n";
        return 1;
    }
    
    if (optLevel != Optimizer::Level::O0) {
        Optimizer::optimize(*codegen.getModule(), optLevel);
    }


    if (emitLlvm) {
        std::cout << codegen.getIRString();
        return 0;
    }

    // ── JIT Execute ─────────────────────────────────────────────────────────
    if (runJit) {
        int exitCode = Executor::run(*codegen.getModule(), "மைய");
        return exitCode;
    }

    // ── Compile to object file -> link to executable ─────────────────────────
    llvm::InitializeNativeTarget();
    llvm::InitializeNativeTargetAsmPrinter();
    llvm::InitializeNativeTargetAsmParser();

    auto targetTriple = llvm::Triple(llvm::sys::getDefaultTargetTriple());
#if LLVM_VERSION_MAJOR >= 18
    codegen.getModule()->setTargetTriple(targetTriple);
#else
    codegen.getModule()->setTargetTriple(targetTriple.getTriple());
#endif

    std::string error;
    auto target = llvm::TargetRegistry::lookupTarget(targetTriple.getTriple(), error);
    if (!target) {
        std::cerr << "பிழை: " << error << "\n";
        return 1;
    }

    auto CPU = "generic";
    auto Features = "";
    llvm::TargetOptions opt;
    auto RM = std::optional<llvm::Reloc::Model>();
#if LLVM_VERSION_MAJOR >= 18
    auto targetMachine = target->createTargetMachine(targetTriple, CPU, Features, opt, RM);
#else
    auto targetMachine = target->createTargetMachine(targetTriple.getTriple(), CPU, Features, opt, RM);
#endif

    codegen.getModule()->setDataLayout(targetMachine->createDataLayout());

    if (outputFile.empty()) {
#ifdef _WIN32
        outputFile = "a.exe";
#else
        outputFile = "a.out";
#endif
    }

    std::error_code ec;
    llvm::raw_fd_ostream dest(outputFile, ec, llvm::sys::fs::OF_None);

    if (ec) {
        std::cerr << "கோப்பினைத் திறக்க முடியவில்லை: " << ec.message() << std::endl;
        return 1;
    }

    llvm::legacy::PassManager pass;
#if LLVM_VERSION_MAJOR >= 18
    auto FileType = llvm::CodeGenFileType::ObjectFile;
#else
    auto FileType = llvm::CGFT_ObjectFile;
#endif

    if (targetMachine->addPassesToEmitFile(pass, dest, nullptr, FileType)) {
        std::cerr << "இந்த வகை கோப்பினை உருவாக்க முடியாது" << std::endl;
        return 1;
    }

    pass.run(*codegen.getModule());
    dest.flush();

    return 0;
}
